apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail
  namespace: mail

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mail

  template:
    metadata:
      labels:
        app: mail

    spec:
      containers:
      - name: mail

        image: mailserver/docker-mailserver:latest

        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 25

        resources:
          requests:
            cpu: 100m
            memory: 128Mi

          limits:
            cpu: 500m
            memory: 512Mi

        readinessProbe:
          tcpSocket:
            port: 25

          initialDelaySeconds: 10
          periodSeconds: 10

        livenessProbe:
          tcpSocket:
            port: 25

          initialDelaySeconds: 30
          periodSeconds: 20
