apiVersion: apps/v1
kind: Deployment

metadata:
  name: cursor-ai-backend
  namespace: openai

spec:
  replicas: 1

  selector:
    matchLabels:
      app: cursor-ai-backend

  template:
    metadata:
      labels:
        app: cursor-ai-backend

    spec:
      containers:
        - name: backend
          image: nginx:alpine

          ports:
            - containerPort: 80

          envFrom:
            - configMapRef:
                name: cursor-config

            - secretRef:
                name: openai-secret

          resources:
            requests:
              cpu: 200m
              memory: 256Mi

            limits:
              cpu: 500m
              memory: 512Mi
