apiVersion: v1
kind: Secret

metadata:
  name: openai-secret
  namespace: openai

type: Opaque

stringData:
  OPENAI_API_KEY: "REPLACE_WITH_REAL_OPENAI_KEY"

  API_BEARER_TOKEN: "e0d3f7aea5c5cfbbf03e3562d88104d7b4a4121968c1a5f9720a3e928ef0f7ce"
