apiVersion: v1
kind: Service

metadata:
  name: openai-service
  namespace: openai

spec:
  selector:
    app: cursor-ai-backend

  ports:
    - name: http
      port: 80
      targetPort: 3001

  type: ClusterIP
