apiVersion: v1
data:
  config.yaml: |
    tunnel: cloudflared-global

    originRequest:
      connectTimeout: 30s
      noTLSVerify: true

    ingress:

      # =========================================
      # ROOT DOMAIN
      # =========================================
      - hostname: shopnoltd.dpdns.org
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80

      # =========================================
      # www ROOT DOMAIN
      # =========================================
      - hostname: www.shopnoltd.dpdns.org
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80

      # =========================================
      # KOBO
      # =========================================
      - hostname: kf.shopnoltd.dpdns.org
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80

      - hostname: kc.shopnoltd.dpdns.org
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80

      - hostname: ee.shopnoltd.dpdns.org
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80

      # =========================================
      # ERP
      # =========================================
      - hostname: erp.shopnoltd.dpdns.org
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80

      # =========================================
      # BILLING
      # =========================================
      - hostname: billing.shopnoltd.dpdns.org
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80

      # =========================================
      # MAILING
      # =========================================
      - hostname: mail.shopnoltd.dpdns.org
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80

      # =========================================
      # STORAGE
      # =========================================
      - hostname: storage.shopnoltd.dpdns.org
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80

      # =========================================
      # MONITORING
      # =========================================
      - hostname: grafana.shopnoltd.dpdns.org
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80

      - hostname: prometheus.shopnoltd.dpdns.org
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80

      # =========================================
      # PORTAINER
      # =========================================
      - hostname: portainer.shopnoltd.dpdns.org
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80

      # =========================================
      # ARGOCD
      # =========================================
      - hostname: argocd.shopnoltd.dpdns.org
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80

      # =========================================
      # WEBSOCKET / REALTIME
      # =========================================
      - hostname: chat.shopnoltd.dpdns.org
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80

      - hostname: meet.shopnoltd.dpdns.org
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80

      - hostname: live.shopnoltd.dpdns.org
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80

      # =========================================
      # WILDCARD
      # =========================================
      - hostname: "*.shopnoltd.dpdns.org"
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80

      # =========================================
      # DEFAULT
      # =========================================
      - service: http_status:404
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"tunnel: cloudflared-global\n\noriginRequest:\n  connectTimeout: 30s\n  noTLSVerify: true\n\ningress:\n\n  # =========================================\n  # ROOT DOMAIN\n  # =========================================\n  - hostname: shopnoltd.dpdns.org\n    service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80\n\n  # =========================================\n  # www ROOT DOMAIN\n  # =========================================\n  - hostname: www.shopnoltd.dpdns.org\n    service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80\n\n  # =========================================\n  # KOBO\n  # =========================================\n  - hostname: kf.shopnoltd.dpdns.org\n    service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80\n\n  - hostname: kc.shopnoltd.dpdns.org\n    service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80\n\n  - hostname: ee.shopnoltd.dpdns.org\n    service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80\n\n  # =========================================\n  # ERP\n  # =========================================\n  - hostname: erp.shopnoltd.dpdns.org\n    service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80\n\n  # =========================================\n  # BILLING\n  # =========================================\n  - hostname: billing.shopnoltd.dpdns.org\n    service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80\n\n  # =========================================\n  # MAILING\n  # =========================================\n  - hostname: mail.shopnoltd.dpdns.org\n    service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80\n\n  # =========================================\n  # STORAGE\n  # =========================================\n  - hostname: storage.shopnoltd.dpdns.org\n    service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80\n\n  # =========================================\n  # MONITORING\n  # =========================================\n  - hostname: grafana.shopnoltd.dpdns.org\n    service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80\n\n  - hostname: prometheus.shopnoltd.dpdns.org\n    service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80\n\n  # =========================================\n  # PORTAINER\n  # =========================================\n  - hostname: portainer.shopnoltd.dpdns.org\n    service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80\n\n  # =========================================\n  # ARGOCD\n  # =========================================\n  - hostname: argocd.shopnoltd.dpdns.org\n    service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80\n\n  # =========================================\n  # WEBSOCKET / REALTIME\n  # =========================================\n  - hostname: chat.shopnoltd.dpdns.org\n    service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80\n\n  - hostname: meet.shopnoltd.dpdns.org\n    service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80\n\n  - hostname: live.shopnoltd.dpdns.org\n    service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80\n\n  # =========================================\n  # WILDCARD\n  # =========================================\n  - hostname: \"*.shopnoltd.dpdns.org\"\n    service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80\n\n  # =========================================\n  # DEFAULT\n  # =========================================\n  - service: http_status:404\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"cloudflared-global-config","namespace":"kube-system"}}
  creationTimestamp: "2026-05-29T11:03:57Z"
  name: cloudflared-global-config
  namespace: kube-system
  resourceVersion: "5414"
  uid: cb4be3b0-1197-4503-a002-822f6d42788b
