apiVersion: batch/v1
kind: Job
metadata:
  name: kobo-db-init
  namespace: kobo
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init
          image: postgres:14
          env:
            - name: PGPASSWORD
              value: change_me
          command:
            - bash
            - -c
            - |
              set -e

              echo "Creating required databases..."

              for DB in kpi kobocat kobo; do
                echo "Checking $DB..."
                psql -h kobo-postgres -U kobo -d postgres -c \
                "CREATE DATABASE $DB;" || echo "$DB exists"
              done
