apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cursor-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: cursor.shopnoltd.dpdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cursor
            port:
              number: 8000
