resources:
  - billing-ingress.yaml
  - chat-ingress.yaml
  - cursor-ingress.yaml
  - ee-ingress.yaml
  - erp-ingress.yaml
  - grafana-ingress.yaml
  - kc-ingress.yaml
  - kf-ingress.yaml
  - kpi-ingress.yaml
  - kustomization.yaml
  - live-ingress.yaml
  - meet-ingress.yaml
  - openai-ingress.yaml
  - prometheus-ingress.yaml
  - root-ingress.yaml
  - www-ingress.yaml
