apiVersion: apps/v1
kind: Deployment

metadata:
  name: roundcube
  namespace: mail

spec:
  replicas: 1

  selector:
    matchLabels:
      app: roundcube

  template:
    metadata:
      labels:
        app: roundcube

    spec:
      containers:
        - name: roundcube

          image: roundcube/roundcubemail:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 80

          env:

            # =========================
            # IMAP (DOVECOT)
            # =========================
            - name: ROUNDCUBEMAIL_DEFAULT_HOST
              value: "tls://dovecot.mail.svc.cluster.local"

            - name: ROUNDCUBEMAIL_DEFAULT_PORT
              value: "143"

            # =========================
            # SMTP (POSTFIX)
            # =========================
            - name: ROUNDCUBEMAIL_SMTP_SERVER
              value: "tls://postfix.mail.svc.cluster.local"

            - name: ROUNDCUBEMAIL_SMTP_PORT
              value: "587"

            # =========================
            # UI
            # =========================
            - name: ROUNDCUBEMAIL_SKIN
              value: "elastic"

            - name: ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE
              value: "50M"

            - name: APACHE_SERVER_NAME
              value: "mail.shopnoltd.dpdns.org"

          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"

            limits:
              memory: "512Mi"
              cpu: "500m"
