apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpi-worker
  namespace: kobo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpi-worker
  template:
    metadata:
      labels:
        app: kpi-worker
    spec:
      containers:
        - name: worker
          image: kobotoolbox/kpi:2.026.13a
          command: ["celery", "-A", "kobo", "worker", "-l", "info"]
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: kobo.settings
            - name: DATABASE_URL
              value: postgres://postgres:postgres@kobo-postgres:5432/kobo
