apiVersion: apps/v1
kind: Deployment

metadata:
  name: chat
  namespace: realtime

spec:
  replicas: 1

  selector:
    matchLabels:
      app: chat

  template:
    metadata:
      labels:
        app: chat

    spec:
      containers:
        - name: chat
          image: nginx:stable

          ports:
            - containerPort: 3000
