apiVersion: apps/v1
kind: Deployment
metadata:
  name: rspamd
  namespace: mail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rspamd
  template:
    metadata:
      labels:
        app: rspamd
    spec:
      containers:
        - name: rspamd
          image: rspamd/rspamd:latest
          ports:
            - containerPort: 11333
