apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ee-ingress
  namespace: default
spec:
  ingressClassName: traefik
  rules:
  - host: ee.shopnoltd.dpdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kf
            port:
              number: 8000
