apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openai-ingress
  namespace: argocd
spec:
  ingressClassName: traefik
  rules:
  - host: openai.shopnoltd.dpdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openai-service
            port:
              number: 80
