apiVersion: v1
kind: ServiceAccount
metadata:
  name: domain-center
  namespace: monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: domain-center
rules:

# Ingresses
- apiGroups: ["networking.k8s.io"]
  resources:
    - ingresses
  verbs:
    - get
    - list

# Services
- apiGroups: [""]
  resources:
    - services
  verbs:
    - get
    - list

# Endpoints
- apiGroups: [""]
  resources:
    - endpoints
  verbs:
    - get
    - list

# Pods
- apiGroups: [""]
  resources:
    - pods
  verbs:
    - get
    - list

# Namespaces
- apiGroups: [""]
  resources:
    - namespaces
  verbs:
    - get
    - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: domain-center
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: domain-center
subjects:
- kind: ServiceAccount
  name: domain-center
  namespace: monitoring
