apiVersion: apps/v1
kind: Deployment

metadata:
  name: cloudflared-global
  namespace: kube-system

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cloudflared-global

  template:
    metadata:
      labels:
        app: cloudflared-global

    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest

          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-global-secret
                  key: TUNNEL_TOKEN

          args:
            - tunnel
            - --no-autoupdate
            - run
            - --config
            - /etc/cloudflared/config/config.yaml

          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            allowPrivilegeEscalation: false

      volumes:
        - name: config
          configMap:
            name: cloudflared-global-config
