protocols = imap

listen = *

log_path = /dev/stdout
info_log_path = /dev/stdout

mail_location = maildir:/mail/%u

disable_plaintext_auth = no
ssl = no

auth_mechanisms = plain login

passdb {
  driver = passwd-file
  args = /etc/dovecot/users
}

userdb {
  driver = static
  args = uid=1000 gid=1000 home=/mail/%u
}

service imap-login {
  inet_listener imap {
    port = 143
  }
}
