apiVersion: v1
kind: Namespace
metadata:
  name: auth

---
apiVersion: v1
kind: Namespace
metadata:
  name: realtime

---
apiVersion: v1
kind: Namespace
metadata:
  name: social

---
apiVersion: v1
kind: Namespace
metadata:
  name: media

---
apiVersion: v1
kind: Namespace
metadata:
  name: ai

---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway

---
apiVersion: v1
kind: Namespace
metadata:
  name: messaging

---
apiVersion: v1
kind: Namespace
metadata:
  name: storage

---
apiVersion: v1
kind: Namespace
metadata:
  name: search
