{{- if .Values.ingress.enabled }}
{{- range $name, $svc := .Values.services }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  namespace: {{ $svc.namespace }}

spec:
  ingressClassName: {{ $.Values.ingress.className }}

  rules:
  - host: {{ $name }}.{{ $.Values.ingress.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $name }}
            port:
              number: {{ $svc.port }}
---
{{- end }}
{{- end }}
