{{- $namespaces := dict }}
{{- range $name, $svc := .Values.services }}
{{- $_ := set $namespaces $svc.namespace true }}
{{- end }}

{{- range $ns, $_ := $namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $ns }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: platform
    meta.helm.sh/release-namespace: platform
---
{{- end }}
