apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: k3s-ha-storage
provisioner: driver.longhorn.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
