apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-ingress.yaml
  - root-ingress.yaml
  - kobo-ingress.yaml
  - erp-ingress.yaml
  - mail-ingress.yaml
  - storage-ingress.yaml
  - monitoring-ingress.yaml
  - portainer-ingress.yaml
  - realtime-ingress.yaml
  - openai-ingress.yaml
  - cursor-ingress.yaml
