apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openai-ingress
  namespace: openai
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - openai.shopnoltd.dpdns.org
      secretName: openai-tls
  rules:
    - host: openai.shopnoltd.dpdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openai
                port:
                  number: 8000
