apiVersion: v1
kind: ConfigMap
metadata:
  name: enketo-config
  namespace: kobo
data:
  config.json: |
    {
      "baseUrl": "http://enketo:8005",
      "redis": {
        "host": "redis",
        "port": 6379
      }
    }
