apiVersion: apps/v1
kind: Deployment

metadata:
  name: enketo
  namespace: kobo

spec:
  replicas: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: enketo

  template:
    metadata:
      labels:
        app: enketo

    spec:
      containers:
        - name: enketo

          image: docker.io/enketo/enketo-express

          imagePullPolicy: Always

          ports:
            - containerPort: 8005

          env:
            - name: PORT
              value: "8005"

            - name: KOBOCAT_URL
              value: "https://kc.shopnoltd.dpdns.org"

            - name: ENKETO_API_TOKEN
              value: "koboenketo"

            - name: NODE_ENV
              value: "production"

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"
