apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: call
  namespace: call

spec:
  ingressClassName: traefik

  rules:
  - host: call.shopnoltd.dpdns.org
    http:
      paths:
      - path: /
        pathType: Prefix

        backend:
          service:
            name: call
            port:
              number: 80
