apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: message
  namespace: message

spec:
  ingressClassName: traefik

  rules:
  - host: message.shopnoltd.dpdns.org
    http:
      paths:
      - path: /
        pathType: Prefix

        backend:
          service:
            name: message
            port:
              number: 80
