apiVersion: v1
kind: ConfigMap

metadata:
  name: cloudflared-billing-config
  namespace: kube-system

data:
  config.yaml: |
    ingress:
      - hostname: billing.shopnoltd.dpdns.org
        service: http://billing-api.erp.svc.cluster.local:8080

      - hostname: api.shopnoltd.dpdns.org
        service: http://gateway.default.svc.cluster.local:8080

      - service: http_status:404
