apiVersion: v1
kind: ConfigMap

metadata:
  name: kobo-env
  namespace: kobo

data:
  DJANGO_DEBUG: "False"

  PUBLIC_DOMAIN_NAME: "shopnoltd.dpdns.org"

  DJANGO_ALLOWED_HOSTS: ".shopnoltd.dpdns.org"

  ALLOWED_HOSTS: ".shopnoltd.dpdns.org,kobocat,kpi,enketo,localhost,127.0.0.1"

  CSRF_TRUSTED_ORIGINS: "https://kc.shopnoltd.dpdns.org,https://kf.shopnoltd.dpdns.org,https://ee.shopnoltd.dpdns.org"

  SESSION_COOKIE_DOMAIN: ".shopnoltd.dpdns.org"

  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"

  REDIS_MAIN_HOST: "redis"
  REDIS_CACHE_HOST: "redis"

  KOBOCAT_URL: "https://kc.shopnoltd.dpdns.org"
  KOBOCAT_PUBLIC_URL: "https://kc.shopnoltd.dpdns.org"
  KOBOCAT_INTERNAL_URL: "http://kobocat:8000"

  KPI_URL: "https://kf.shopnoltd.dpdns.org"
  KPI_INTERNAL_URL: "http://kpi:8000"

  KPIENKETO_URL: "https://ee.shopnoltd.dpdns.org"

  ENKETO_URL: "https://ee.shopnoltd.dpdns.org"

  DJANGO_SETTINGS_MODULE: "kobo.settings.production"

  DATABASE_URL: "postgres://kobo:kobo@postgres:5432/postgres"

  KC_DATABASE_URL: "postgres://kobo:kobo@postgres:5432/kobocat"

  CACHE_URL: "redis://redis:6379/1"

  CELERY_BROKER_URL: "redis://redis:6379/2"

  MONGO_DB_URL: "mongodb://mongo:27017/kpi"
