apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kobo

resources:
  - kpi/deployment.yaml
  - kobocat/deployment.yaml
  - enketo/deployment.yaml
  - kpi-worker/deployment.yaml
  - kobo-postgres/statefulset.yaml
  - enketo/configmap.yaml

