apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kobo

resources:
  - namespace.yaml
  - postgres
  - redis
  - kpi
  - kobocat
  - worker
  - enketo
  - ingress.yaml
  - init/db-init-job.yaml
