apiVersion: v1
kind: ConfigMap
metadata:
  name: kobo-env
  namespace: kobo

data:
  DJANGO_ALLOWED_HOSTS: .shopnoltd.dpdns.org
  DJANGO_DEBUG: "False"

  PUBLIC_DOMAIN_NAME: shopnoltd.dpdns.org

  REDIS_MAIN_HOST: redis
  REDIS_CACHE_HOST: redis

  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"

  KOBOCAT_URL: "https://kc.shopnoltd.dpdns.org"
  KPI_URL: "https://kf.shopnoltd.dpdns.org"
  KPIENKETO_URL: "https://ee.shopnoltd.dpdns.org"

  KOBOFORM_URL: "https://kf.shopnoltd.dpdns.org"
  KOBOCAT_PUBLIC_URL: "https://kc.shopnoltd.dpdns.org"

  KOBOCAT_INTERNAL_URL: "http://kobocat:8000"
  KPI_INTERNAL_URL: "http://kpi:8000"
  
  
  SESSION_COOKIE_DOMAIN: .shopnoltd.dpdns.org

  CSRF_TRUSTED_ORIGINS: "https://kc.shopnoltd.dpdns.org,https://kf.shopnoltd.dpdns.org,https://ee.shopnoltd.dpdns.org"

  ALLOWED_HOSTS: ".shopnoltd.dpdns.org,kobocat,kpi,localhost,127.0.0.1"
