apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai
  namespace: ai
spec:
  ingressClassName: traefik

  tls:
  - secretName: wildcard-shopnoltd
    hosts:
    - ai.shopnoltd.dpdns.org
    - www.ai.shopnoltd.dpdns.org

  rules:

  - host: ai.shopnoltd.dpdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ai-frontend
            port:
              number: 3000

  - host: www.ai.shopnoltd.dpdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ai-frontend
            port:
              number: 3000

