apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: code
  namespace: dev
spec:
  ingressClassName: traefik

  tls:
  - secretName: wildcard-shopnoltd
    hosts:
    - code.shopnoltd.dpdns.org
    - www.code.shopnoltd.dpdns.org

  rules:

  - host: code.shopnoltd.dpdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: code-server
            port:
              number: 8080

  - host: www.code.shopnoltd.dpdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: code-server
            port:
              number: 8080

