apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: domain-registry
spec:
  ingressClassName: traefik

  rules:

  - host: api.shopnoltd.dpdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: domain-registry
            port:
              number: 8000

  - host: www.api.shopnoltd.dpdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: domain-registry
            port:
              number: 8000
