apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kobo
  namespace: kobo
spec:
  ingressClassName: traefik

  tls:
  - secretName: wildcard-shopnoltd
    hosts:
    - kobo.shopnoltd.dpdns.org
    - www.kobo.shopnoltd.dpdns.org

  rules:

  - host: kobo.shopnoltd.dpdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shopnoltd-toolbox
            port:
              number: 80

  - host: www.kobo.shopnoltd.dpdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shopnoltd-toolbox
            port:
              number: 80

