apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - root.yaml
  - api.yaml
  - ai.yaml
  - openai.yaml
  - chat.yaml
  - blog.yaml
  - mail.yaml
  - meeting.yaml
  - code.yaml
  - kobo.yaml
  - erp.yaml
  - billing.yaml
  - social.yaml
