apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test6
  namespace: default
spec:
  ingressClassName: traefik

  tls:
  - secretName: wildcard-shopnoltd
    hosts:
    - test6.shopnoltd.dpdns.org

  rules:

  - host: test6.shopnoltd.dpdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chat-ui
            port:
              number: 80

