apiVersion: apps/v1
kind: Deployment

metadata:
  name: kobocat
  namespace: kobo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: kobocat

  template:
    metadata:
      labels:
        app: kobocat

    spec:
      containers:
        - name: kobocat

          image: kobotoolbox/kobocat:latest

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          env:
            - name: DJANGO_SETTINGS_MODULE
              value: kobocat.settings.kobo

            - name: KOBOCAT_DATABASE_NAME
              value: kobocat

            - name: KOBOCAT_DATABASE_USER
              value: postgres

            - name: KOBOCAT_DATABASE_PASSWORD
              value: postgres

            - name: KOBOCAT_DATABASE_HOST
              value: postgres.kobo.svc.cluster.local

            - name: KOBOCAT_REDIS_URL
              value: redis://redis.kobo.svc.cluster.local:6379/1

            - name: KOBO_URL
              value: https://kf.shopnoltd.dpdns.org

            - name: KOBOCAT_URL
              value: https://kc.shopnoltd.dpdns.org

            - name: ENKETO_URL
              value: https://ee.shopnoltd.dpdns.org

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"

            limits:
              cpu: "1"
              memory: "1Gi"
