apiVersion: apps/v1
kind: Deployment

metadata:
  name: kobocat
  namespace: kobo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: kobocat

  template:
    metadata:
      labels:
        app: kobocat

    spec:
      containers:
        - name: kobocat
          image: kobotoolbox/kobocat:2.026.13a
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          env:
            - name: KOBO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kobo-db-secret
                  key: password

            - name: DATABASE_URL
              value: postgres://kobo:$(KOBO_DB_PASSWORD)@kobo-postgres.kobo.svc.cluster.local:5432/kobocat

            - name: CELERY_BROKER_URL
              value: redis://kobo-redis.kobo.svc.cluster.local:6379/1

            - name: KOBOCAT_DJANGO_SECRET_KEY
              value: super-secret-kobocat-key

            - name: ALLOWED_HOSTS
              value: "*"

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 10

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 10
