apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp
  namespace: erp

spec:
  replicas: 1

  selector:
    matchLabels:
      app: erp

  template:
    metadata:
      labels:
        app: erp

    spec:
      containers:
      - name: erp
        image: frappe/erpnext:latest
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8000

        resources:
          requests:
            cpu: 100m
            memory: 128Mi

          limits:
            cpu: 500m
            memory: 512Mi

        readinessProbe:
          tcpSocket:
            port: 8000

          initialDelaySeconds: 10
          periodSeconds: 10

        livenessProbe:
          tcpSocket:
            port: 8000

          initialDelaySeconds: 30
          periodSeconds: 20
