apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp
  namespace: erp

spec:
  replicas: 1

  selector:
    matchLabels:
      app: erp

  template:
    metadata:
      labels:
        app: erp

    spec:
      containers:
      - name: erp
        image: frappe/erpnext

        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8000
