apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-studio
  namespace: default
spec:
  ingressClassName: traefik
  rules:
  - host: ai.shopnoltd.dpdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ai-frontend
            port:
              number: 3000
