apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - billing
  - erp
  - kobo
  - mail
  - messaging
  - monitoring
  - queue
  - realtime
  - social
  - storage
  - turn
  - webrtc
