apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kobo
  - erp
  - billing
  - monitoring
  - storage
  - queue
  - realtime
  - messaging
  - social
  - notifications
  - tools/portainer
