apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-loader
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://gitlab.com/asaduzzaman.bheramara-group/k8s-platform.git
    targetRevision: main
    path: apps

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
