apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cursor-ingress
  namespace: cursor
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - cursor.shopnoltd.dpdns.org
      secretName: cursor-tls
  rules:
    - host: cursor.shopnoltd.dpdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cursor-app
                port:
                  number: 3000
