apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: erp-ingress
  namespace: erp
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - erp.shopnoltd.dpdns.org
        - billing.shopnoltd.dpdns.org
        - api.erp.shopnoltd.dpdns.org
      secretName: erp-tls
  rules:
    - host: erp.shopnoltd.dpdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: erp-app
                port:
                  number: 8080
    - host: billing.shopnoltd.dpdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: erp-billing
                port:
                  number: 8000
    - host: api.erp.shopnoltd.dpdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: erp-api
                port:
                  number: 8000
