apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../generated/openai
  - ../generated/erp
  - ../generated/mail
  - ../generated/social
  - ../generated/toolbox
  - ../generated/monitoring
