apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../appsets/platform-services.yaml

  - ../applications/kobo.yaml
  - ../applications/erp.yaml
  - ../applications/mail.yaml
  - ../applications/portainer.yaml
  - ../applications/cloudflared-global.yaml
  - ../applications/openai.yaml
  - ../applications/storage.yaml
  - ../applications/realtime.yaml
  - ../applications/cursor.yaml
