apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-api
  namespace: erp

spec:
  replicas: 1

  selector:
    matchLabels:
      app: billing-api

  template:
    metadata:
      labels:
        app: billing-api

    spec:
      containers:
        - name: billing-api
          image: hashicorp/http-echo

          args:
            - "-text=Shopno Database Firm Billing System"
            - "-listen=:8080"

          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: billing-api
  namespace: erp

spec:
  selector:
    app: billing-api

  ports:
    - port: 8080
      targetPort: 8080

  type: ClusterIP
