apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openai
  namespace: openai
spec:
  ingressClassName: traefik

  tls:
  - secretName: wildcard-shopnoltd
    hosts:
    - openai.shopnoltd.dpdns.org
    - www.openai.shopnoltd.dpdns.org

  rules:

  - host: openai.shopnoltd.dpdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openai
            port:
              number: 8000

  - host: www.openai.shopnoltd.dpdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openai
            port:
              number: 8000

