apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: realtime-chat-ingress
  namespace: argocd
spec:
  ingressClassName: traefik
  rules:
  - host: chat.shopnoltd.dpdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: realtime-chat
            port:
              number: 80
