apiVersion: apps/v1
kind: Deployment

metadata:
  name: rabbitmq
  namespace: messaging

spec:
  replicas: 1

  selector:
    matchLabels:
      app: rabbitmq

  template:
    metadata:
      labels:
        app: rabbitmq

    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management

          ports:
            - name: amqp
              containerPort: 5672

            - name: management
              containerPort: 15672

          env:
            - name: RABBITMQ_DEFAULT_USER
              value: admin

            - name: RABBITMQ_DEFAULT_PASS
              value: AYFMcHQ5yyYBXW9fvrT6EtCdX4KCwVMaLricTqCYcJ0=

          resources:
            requests:
              cpu: 250m
              memory: 512Mi

            limits:
              cpu: "1"
              memory: 2Gi
