apiVersion: apps/v1
kind: Deployment

metadata:
  name: odoo
  namespace: erp

spec:
  replicas: 1

  selector:
    matchLabels:
      app: odoo

  template:
    metadata:
      labels:
        app: odoo
        topology.kubernetes.io/zone: home

    spec:
      containers:
        - name: odoo
          image: odoo:17
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8069

          env:
            - name: HOST
              value: postgres.erp.svc.cluster.local

            - name: USER
              value: erp

            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password

            - name: DB_NAME
              value: erp

            - name: DB_PORT
              value: "5432"

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"

            limits:
              cpu: "1"
              memory: "1Gi"

          readinessProbe:
            httpGet:
              path: /web/login
              port: 8069
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 10

          livenessProbe:
            httpGet:
              path: /web/login
              port: 8069
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 10
