apiVersion: apps/v1
kind: Deployment

metadata:
  name: odoo
  namespace: erp

spec:
  replicas: 1

  selector:
    matchLabels:
      app: odoo

  template:
    metadata:
      labels:
        app: odoo

    spec:
      containers:
        - name: odoo

          image: odoo:17

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8069

          env:
            - name: HOST
              value: postgres.erp.svc.cluster.local

            - name: USER
              value: odoo

            - name: PASSWORD
              value: odooStrongPassword123!

            - name: DB_NAME
              value: erp

            - name: DB_PORT
              value: "5432"

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"

            limits:
              memory: "1Gi"
              cpu: "1000m"

          readinessProbe:
            httpGet:
              path: /
              port: 8069
            initialDelaySeconds: 40
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 8069
            initialDelaySeconds: 80
            periodSeconds: 20
